version: "3.7"

services:
  redis:
    env_file: ./environments/.dev.env
    image: redis:5.0.4-stretch
    stop_grace_period: -3s
    ports:
      - 6379:6379
    volumes:
      - redis:/data
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]

  web:
    env_file: ./environments/.dev.env
    build: ./services/web
    depends_on:
      - redis
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000

volumes:
  redis:
